- hosts: all
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Create custom DNS object
      cisco.fmcansible.fmc_configuration:
        operation: upsertDNSServerGroupObject
        data:
          type: DNSServerGroupObject
          name: "{{ dnsserevergroup_name | default('CustomDNSServerGroup') }}"
          timeout: 2
          retries: 3
          defaultdomain: cisco.com
          dnsservers:
            - name-server: "{{ dnsserver1_ip | default('1.2.3.4') }}"
            - name-server: "{{ dnsserver2_ip | default('2.2.3.4') }}"
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
