- hosts: all
  gather_facts: False
  any_errors_fatal: true
  connection: httpapi
  tasks:
    - name: Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain
    
    - name: Get Access Policy
      cisco.fmcansible.fmc_configuration:
        operation: getAllAccessPolicy
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        filters:
          name: test
        register_as: accesspolicy
    
    - name: Get Server Version
      cisco.fmcansible.fmc_configuration:
        operation: getAllServerVersion
        register_as: server_version

    - name: Device onboarding for < 7.X
      when: server_version[0].serverVersion is regex("[0-6]\.[0-9]+\.[0-9]+")
      cisco.fmcansible.fmc_configuration:
        operation: upsertDevice
        data:
          hostName: "10.0.2.11"
          license_caps:
            - 'BASE'
          ftdMode: 'ROUTED'
          type: Device
          regKey: cisco
          name: "FTD1"
          accessPolicy:
            id: '{{ accesspolicy[0].id }}'
            type: 'AccessPolicy'
          natID: '1234'
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        register_as: ftd

    - name: Device onboarding for >= 7.X
      when: server_version[0].serverVersion is not regex("[0-6]\.[0-9]+\.[0-9]+")
      cisco.fmcansible.fmc_configuration:
        operation: createMultipleDevice
        data:
          - hostName: "10.0.2.11"
            license_caps:
              - 'BASE'
            ftdMode: 'ROUTED'
            type: Device
            regKey: cisco
            performanceTier: "FTDv30"
            name: "FTD1"
            accessPolicy:
              id: '{{ accesspolicy[0].id }}'
              type: 'AccessPolicy'
            natID: '1234'
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        query_params:
          bulk: true
        register_as: ftd

    - name: Verify whether device is registered
      cisco.fmcansible.fmc_configuration:
        operation: getAllDevice
        path_params:
          domainUUID: '{{ domain[0].uuid }}' 
        register_as: device_list
      until: (device_list | length) != 0
      retries: 30
      delay: 10
