- hosts: all
  gather_facts: False
  any_errors_fatal: true
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Get Access Policy
      cisco.fmcansible.fmc_configuration:
        operation: getAllAccessPolicy
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        # filters:
        #   name: NGFW-Access-Policy27
        register_as: accesspolicy

    - name: device onboarding
      cisco.fmcansible.fmc_configuration:
        operation: createMultipleDevice
        data:
          hostName: "{{ ftd_ip | default('1.1.1.1') }}"
          license_caps:
            - 'BASE'
          ftdMode: 'ROUTED'
          type: Device
          regKey: "{{ reg_key | default('cisco') }}"
          performanceTier: "FTDv30"
          name: "{{ ftd_name | default('FTD1') }}"
          accessPolicy:
            id: '{{ accesspolicy[0].id }}'
            type: 'AccessPolicy'
          natID: "{{ nat_id | default('') }}"
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        register_as: ftd
