- hosts: all
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Create an FQDN network for Cisco DevNet
      cisco.fmcansible.fmc_configuration:
        operation: upsertDNSServerGroupObject
        data:
          name: "{{ dnsserevergroup_name | default('DNSGroup2') }}"
          dnsservers:
            - name-server: "{{ dnsserver1_ip | default('2.2.2.4') }}"
            - name-server: "{{ dnsserver2_ip | default('3.3.3.3') }}"
          type: DNSServerGroupObject
        path_params:
          domainUUID: '{{ domain[0].uuid }}'

    # - name: Delete FQDN network for Cisco DevNet
    #   cisco.fmcansible.fmc_configuration:
    #     operation: deleteDNSServerGroupObject
    #     path_params:
    #       domainUUID: '{{ domain[0].uuid }}'
    #       objectId: '{{ DNSServerGroupObject_dnsgroup2.id }}'
