namespace: cisco
name: fmcansible
version: 1.0.4
readme: README.md

authors:
  - joe Agster <joeaxcdw>
  - Iurii Tymoshevskyi <itymo>
  - Sameer Singh <sameesin>
  - Jeroen Wittock

description: An Ansible collection for managing Cisco Secure Firewall Management Center

license_file: "LICENSE"

tags:
  - "cisco"
  - "security"
  - "firewall"
  - "fmc"
  - "ftd"

python_requires: ">=3.6"

dependencies:
  community.general: '>=7.5.9'
  community.network: '5.0.3'
  ansible.netcommon: '5.3.0'
  ansible.utils: '5.1.2'
  python:
    - urllib3>=1.26.0
    - requests>=2.25.0

repository: https://github.com/CiscoDevNet/FMCAnsible
homepage: https://github.com/CiscoDevNet/FMCAnsible
issues: https://github.com/CiscoDevNet/FMCAnsible/issues

build_ignore: []
