namespace: cisco
name: fmcansible
version: 1.1.0
readme: README.md

authors:
  - joe Agster <joeaxcdw>
  - Iurii Tymoshevskyi <itymo>
  - Sameer Singh <sameesin>
  - Jeroen Wittock <jwittock>
  - Charan Teja <teande>
  - Suraj Netla Mundaje <snetlamu>

description: An Ansible collection for managing Cisco Secure Firewall Management Center

license_file: "LICENSE"

tags:
  - "cisco"
  - "security"
  - "firewall"
  - "fmc"
  - "ftd"
  - "automation"

dependencies:
  community.general: ">=7.5.9"
  community.network: "5.0.3"
  ansible.netcommon: "5.3.0"
  ansible.utils: "5.1.2"

repository: https://github.com/CiscoDevNet/FMCAnsible
homepage: https://github.com/CiscoDevNet/FMCAnsible
issues: https://github.com/CiscoDevNet/FMCAnsible/issues

build_ignore: []
