namespace: cisco
name: fmcansible
version: 0.9.1
readme: README.md

authors:
  - joe Agster <joeaxcdw>
  - Iurii Tymoshevskyi <itymo>
  - Sameer Singh <sameesin>

description: An Ansible collection for managing Cisco Secure Firewall Management Center

license_file: "LICENSE"

tags:
  - "cisco"
  - "security"
  - "firewall"
  - "fmc"
  - "ftd"

dependencies:
  community.general: '>=6.5.0'
  community.network: 5.0.0
  ansible.netcommon: 5.1.0
  ansible.utils: 2.9.0

repository: https://github.com/CiscoDevNet/FMCAnsible
homepage: https://github.com/CiscoDevNet/FMCAnsible
issues: https://github.com/CiscoDevNet/FMCAnsible/issues

build_ignore: []
