- name: Collect FMC Access Policies and Rules
  hosts: vfmc
  gather_facts: no
  connection: httpapi
  collections:
    - cisco.fmcansible
  tasks:
    - name: Get all access policies
      cisco.fmcansible.fmc_configuration:
        operation: getAllAccessPolicy
        path_params:
          domainUUID: "your-domain-uuid-here"  # Replace with your actual domain UUID
      register: access_policies

    - name: Process each access policy
      include_tasks: process_policy.yml
      loop: "{{ access_policies.response['items'] }}"
      loop_control:
        loop_var: policy
      when: access_policies is defined and access_policies | length > 0