---
- name: Collect FMC Access Policies and Rules
  hosts: vfmc
  gather_facts: no
  connection: httpapi
  collections:
    - cisco.fmcansible
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory
      delegate_to: localhost
      run_once: true
      become: false
      register: dir_info

  roles:
    - role: get_access_policies
