---
galaxy_info:
  role_name: get_ha_devices
  author: Cisco Systems
  description: Role to retrieve FTD HA device containers from Cisco FMC
  company: Cisco Systems, Inc.
  license: GPL-3.0-or-later
  min_ansible_version: 2.10.0

  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all

  galaxy_tags:
    - cisco
    - firepower
    - fmc
    - security
    - networking
    - ha
    - high-availability

dependencies: []
