- hosts: all
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Allow traffic by default
      cisco.fmcansible.fmc_configuration:
        operation: "createAccessPolicy"
        data:
            type: "AccessPolicy"
            name: "{{accesspolicy_name | default('AccessPolicy1') }}"
            defaultAction: {'action': 'TRUST'}
        path_params:
            domainUUID: "{{ domain[0].uuid }}"
