- hosts: all
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Create security zone - Inside
      cisco.fmcansible.fmc_configuration:
        operation: createMultipleSecurityZoneObject
        data:
          name: "{{securityzone1_name | default('secz1') }}"
          interfaceMode: ROUTED
          type: SecurityZone
        path_params:
          domainUUID: '{{ domain[0].uuid }}'

    - name: Create security zone - Outside
      cisco.fmcansible.fmc_configuration:
        operation: createMultipleSecurityZoneObject
        data:
          name: "{{securityzone2_name | default('secz2') }}"
          interfaceMode: ROUTED
          type: SecurityZone
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
